http:
  host: 127.0.0.1
  port: 3000

database:
  host: 127.0.0.1
  port: 27017
  db: socketchat
  username: root
  password: root

jwt:
  secret: ffc380d8c8a80cfee58441de02889c77
  expiration: 30d
