version: "3.9"

services:
  chat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - network
    depends_on:
      - db
  db:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - network
networks:
  network:
    driver: bridge
