version: "3.9"

services:
  chat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - network
    depends_on:
      - db
    environment:
      - NODE_ENV=development
  db:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    command: mongod --port 28017
    ports:
      - 127.0.0.1:28017:28017
    networks:
      - network
networks:
  network:
    driver: bridge
